#define use_PSU_state 0

#define RESET_CMD_GPIO 4
#define POWER_CMD_GPIO 12
#define GET_MOTHERBOARD_ON_STATE_GPIO 14
#define GET_MOTHERBOARD_POWER_STATE_GPIO 13

#define LOOP_DELAY_MS 50
#define LONG_PRESS_MS 4500
#define SHORT_PRESS_MS 500

#define RESET_DURATION_MS SHORT_PRESS_MS
#define POWEROFF_DURATION_MS LONG_PRESS_MS
#define POWERON_DURATION_MS SHORT_PRESS_MS

#define OPEN_SW LOW
#define CLOSED_SW !OPEN_SW
#define ON_STATE HIGH
#define OFF_STATE LOW
